version: '3.7'

services:
  node:
    build: ./docker/node
    tty: true
    #command: bash -c "npm i "
    container_name: node-salary-calculator-container
    volumes:
      - .:/www
    ports:
      - "3998:3000"

volumes:
  node_modules:
  data:
    driver: "local"
